comment out `emerge --sync` for avoid #2.

diff --git a/Dockerfile.d/Dockerfile b/Dockerfile.d/Dockerfile
--- a/Dockerfile.d/Dockerfile
+++ b/Dockerfile.d/Dockerfile
@@ -39,8 +39,10 @@ RUN locale-gen
 # Required git for portage git repositories.
 # see also: https://wiki.gentoo.org/wiki/Project:Portage/Sync
 RUN emerge -uvq dev-vcs/git
-# accept any return code, because rsync servers sometimes return errors.
-RUN (timeout 3m emerge --sync --quiet; exit 0)
+# Fixme: Avoid build failure on GitHub Actions captures.
+# ref. https://github.com/mazgi/docker.gentoo/issues/2
+## Accept any return code, because rsync servers sometimes return errors.
+## RUN (timeout 3m emerge --sync --quiet || true)
 # basic packages
 RUN emerge -uvq \
   app-admin/sudo \
